### ISSUE TITLE
Change default AWS_ENVIRONMENT to PRODUCTION

### ISSUE THREAD

**Issue by drewxa** [denisneuf/python-amazon-ad-api#175]
According to https://advertising.amazon.com/API/docs/en-us/release-notes/archive/ads-api#sandbox-deprecation-on-june-28-2022, the sandbox environment has been deprecated, and you should use test accounts. Currently, by default, the API is accessing a non-functional API.

```
ad_api.base.exceptions.AdvertisingApiTemporarilyUnavailableException: (503, b'<html><body><b>Http/1.1 Service Unavailable</b></body> </html>', {'Server': 'Server', 'Date': 'Fri, 18 Aug 2023 11:17:45 GMT', 'Content-Length': '62', 'Connection': 'keep-alive', 'x-amz-rid': 'AN6Y4P8YF3MQCX4EKQN4', 'Cache-Control': 'no-cache,no-store', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload'})
```

**Comment by denisneuf** [comment]
Hi @drewxa last time I tried the sandbox was still working, I will confirm that is unavailable and in that case we don't need the .env anymore so I will remove for next versions just in case and update the README file
