### ISSUE TITLE
Unuthorized exception when switching endpoints

### ISSUE THREAD

**Issue by Jakobovski** [denisneuf/python-amazon-ad-api#188]
Thanks for making this useful library! 

There seems to be a bug with the API caching authentication data or maybe API endpoints URLs.

When I use the API to connect to a US marketplace and then try to connect to an EU marketplace without restarting the application I receive a 401 unauthorized. 

I have a script that loops through all the marketplaces I sell in and adjusts bids. It is inconvenient to need to restart the application for this to work

**Comment by drewxa** [comment]
Hi @Jakobovski 
Thx for reporting

Could you share a code example or snippet related to your case? This will help us investigate the issue more effectively.

**Comment by Jakobovski** [comment]
Here is some sample code

```
import os

from ad_api.base import Marketplaces

MARKETPLACES = [
    {
        'obj': Marketplaces.US,
        'profile_id': 'xxx',
    },
    {
        'obj': Marketplaces.CA,
        'profile_id': 'xxx',
    },
    {
        'obj': Marketplaces.DE,
        'profile_id': 'xxx',
    },
    {
        'obj': Marketplaces.FR,
        'profile_id': 'xxx',
    }]



def login(profile_id):
    API_CLIENT_ID = 'xxxxxxxxx'
    API_CLIENT_SECRET = 'xxxxxxxxxx'
    API_PROFILE_ID = profile_id
    AWS_REFRESH_TOKEN = 'xxxxxxxxx'

    os.environ.setdefault('AD_API_REFRESH_TOKEN', AWS_REFRESH_TOKEN)
    os.environ.setdefault('AD_API_CLIENT_ID', API_CLIENT_ID)
    os.environ.setdefault('AD_API_CLIENT_SECRET', API_CLIENT_SECRET)
    os.environ.setdefault('AD_API_PROFILE_ID', API_PROFILE_ID)
    os.environ.setdefault('AWS_ENV', 'PRODUCTION')



for marketplace in MARKETPLACES:
    login(marketplace['profile_id'])
    
    # After we loop through US and Canada and try to make a call to the DE (europe) marketplace it will fail with HTTP unauthorized, 
    # For example, this will fail
    body = {...}
    result = Reports(marketplace=marketplace).post_report(body=body)

    
    
    
```

**Comment by Jakobovski** [comment]
Furthermore, I just noticed a really bad bug that cost me a lot of money.

I was running the code above but instead of generating reports in the loop it was adjusting bids. It turns out it was not properly switching marketplaces. So when i thought it was changing the prices in Canada it was really changing the prices in the US to what the canadian prices should have been. 

So now i have learned to need to re-run the application for each marketplace even if the share the same API endpoint. This is inconvenient.

**Comment by Jakobovski** [comment]
Nevermind it was my mistake, I was using ` os.environ.setdefault`

Sorry to bother you.
