### ISSUE TITLE
When the report is empty, the value of payload is the response header.

### ISSUE THREAD

**Issue by mkdir700** [denisneuf/python-amazon-ad-api#2]
**Describe the bug**
When the report is empty, the value of payload is the response header.

I don't understand the intention of this practice.

**To Reproduce**
1. Get an empty Report
2. View this ApiResponse.payload

![image](https://user-images.githubusercontent.com/56359329/140596652-a287a822-de2d-42de-a378-f704e3a9e21d.png)

**Expected behavior**
If the report is empty, I think payload should also be empty, not the response header.

**Comment by denisneuf** [comment]
Ok I will have a look and check later.

**Comment by denisneuf** [comment]
Hi could you share your python code to "Get an empty Report"? 
I don't know how to reproduce your problem.
If I tried a empty report like this:
```

import logging
import json
from ad_api.base import AdvertisingApiException, Marketplaces
from ad_api.api.sp.reports import Reports

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s:%(levelname)s:%(message)s"
)

try:

    # report_id = 'amzn1.clicksAPI.v1.m44551.6189D022.4543b157-d833-4bc5-a982-be6ec337b9530'
    report_id = 'empty'

    result = Reports().get_report(
        reportId=report_id
    )
    logging.info(result)


except AdvertisingApiException as ex:
    print(ex)

```

I get this payload:

`{'code': 'NOT_FOUND',
             'details': 'Report is not found by provided report identifier: '
                        "'empty'.",
             'requestId': '8133FSPAEPM4V6MK4XCV'}}`

**Comment by mkdir700** [comment]
hi, guys! I'm sorry for the mistake in my expression.

I mean the result of the download is an empty list.

**Comment by mkdir700** [comment]
https://github.com/denisneuf/python-amazon-ad-api/blob/2cc9be0f789c21e58b0b79d9c2e0bd9d55c7e111/ad_api/base/api_response.py#L5
i think:
```
self.payload = payload
```

**Comment by denisneuf** [comment]
Got it, already updated. Kindest regards.
