### ISSUE TITLE
Support for SB Category Benchmarks

### ISSUE THREAD

**Issue by JTimings** [denisneuf/python-amazon-ad-api#206]
Great library! Is there a timeline for adding support for [Category benchmarks](https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/category-benchmark)? This feature would be great for advertisers looking to measure their performance against their peers.

**Comment by denisneuf** [comment]
Hi @JTimings , I will have a look and add for next version but I can't confirm when could be available, if you want create a PR I will be happy to add. Thanks for understanding.

**Comment by denisneuf** [comment]
v0.5.8

**Comment by denisneuf** [comment]
completed @JTimings you can test
