### ISSUE TITLE
I would like to suggest this method name for edit_ad_groups for update ad groups in sponsored brand.

### ISSUE THREAD

**Issue by leollon** [denisneuf/python-amazon-ad-api#212]
Since the request body for update ad groups in sponsored products is as follows:
```
{
  "adGroups": [
    {
      "name": "string",
      "state": "ENABLED",
      "adGroupId": "string",
      "defaultBid": 0.1
    }
  ]
}
```
When sending request for [updating ad groups](https://github.com/denisneuf/python-amazon-ad-api/blob/b16032e6b74ea31f01edb86885efe214f6333e1c/ad_api/api/sp/ad_groups_v3.py#L55), it is like:

```python
return self._request(kwargs.pop('path'), data=Utils.convert_body(kwargs.pop('body'), False), params=kwargs, headers=headers)
```

meanwhile the request body for updating ad groups in sponsored brand:

```
{
  "adGroups": [
    {
      "name": "string",
      "state": "ENABLED",
      "adGroupId": "string"
    }
  ]
}
```
When sending request for [updating ad groups](https://github.com/denisneuf/python-amazon-ad-api/blob/b16032e6b74ea31f01edb86885efe214f6333e1c/ad_api/api/sb/ad_groups_v4.py#L47)

```python
return self._request(kwargs.pop('path'), data=Utils.convert_body(kwargs.pop('body'), False) , params=kwargs, headers=headers)
```

Therefore, they have something in common. when update this two kinds of ad group in a loop `while`, it could goes like:

````python
def demo(ad_group_category = "sp"):
    ad_group_class = {"sb": "AdGroupsV4", "sp": "adGroupv3"}
    ad_group_client = ad_group_class["ad_group_category"]
    ad_groups = [{"name": "demo", "adGroupId": "123458992",  "state": "ENABLED"}]
   try:
       ad_group_client.edit_ad_groups(body={"adGroups": ad_groups})
   except Exception:
       pass
````

**Comment by denisneuf** [comment]
#213
