### ISSUE TITLE
In V3 version, the filters in list_campaigns don't seem to be working

### ISSUE THREAD

**Issue by baisedongtian** [denisneuf/python-amazon-ad-api#214]
ad_creator = AmazonAdCreator(**config)
    test_filters = {
        "nameFilter": {
            "value": "test campaign",
            "queryTermMatchType": "BROAD_MATCH"
        },

    }
    
    try:
     
        response = ad_creator.campaign_client.list_campaigns(
            body=test_filters
        )

        print(response)
  except Exception as e:
---------------------------------------------------
In this code, the nameFilter doesn't seem to be working - it keeps returning all campaigns.

**Comment by denisneuf** [comment]
Check with the correct dictionary:

```
    test_filters = \
        {
            "nameFilter": {
                "queryTermMatchType": "BROAD_MATCH",
                "include": [
                    "test campaign"
                ]
            }
        }
```
Let me know if works for you and I will close it

**Comment by baisedongtian** [comment]
The query is working normally now, thank you for your help！
