### ISSUE TITLE
SB Snapshots

### ISSUE THREAD

**Issue by denisneuf** [denisneuf/python-amazon-ad-api#38]
### Discussed in https://github.com/denisneuf/python-amazon-ad-api/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **KiranKowlgi** April  6, 2022</sup>
Hi,

Great work on the package. It's very useful so thank you so much. I wanted to check if you were planning to add the SB Snapshots API to the package? thanks again</div>

**Comment by denisneuf** [comment]
Hi, yes. The idea is to cover all the endpoints so I will add later. Recently I am busy with some other projects and not sure when I could add, test and push. Hope is soon.
Kindest Regards.

**Comment by denisneuf** [comment]
Well I had a look and was pretty easy to add as was almost the same than the sponsored_display and sponsored_product, just changing the endpoint.

So you could use at follows:

`from ad_api.api import sponsored_brands`

1) Post the snapshot to get the snapshot_id

```
def sb_post_snapshot():

    logging.info("---------------------------------")
    logging.info("Sponsored Brands")
    logging.info("---------------------------------")

    record_type = "campaigns"  # campaigns, or keywords
    state_filter = "paused"  # enabled, paused, archived

    dictionary = {
        "stateFilter": state_filter,
    }

    result = sponsored_brands.Snapshots(account=store, marketplace=marketplace, debug=True).post_snapshot(
        recordType=record_type,
        body=json.dumps(dictionary)
    )

    payload = result.payload

    logging.info(payload)
```

Api Response

{'snapshotId': 'amzn1.clicksAPI.v1.p44551.624D0FA2.60f2effe-6dfe-4a0c-9bef-123456789', 'recordType': 'keyword', 'status': 'IN_PROGRESS'}

2) Get the status of the snapshot to collect the url

```
def sb_get_snapshot():

    snapshot_id = 'amzn1.clicksAPI.v1.p44551.624D0FA2.60f2effe-6dfe-4a0c-9bef-123456789'

    result = sponsored_brands.Snapshots(account=store, marketplace=marketplace, debug=True).get_snapshot(
        snapshotId=snapshot_id
    )

    payload = result.payload

    logging.info(payload)
```

Api Response

{'snapshotId': 'amzn1.clicksAPI.v1.p44551.624D0FA2.60f2effe-6dfe-4a0c-9bef-123456789', 'status': 'SUCCESS', 'statusDetails': 'Snapshot has been successfully generated.', 'location': 'https://advertising-api-eu.amazon.com/v1/snapshots/amzn1.clicksAPI.v1.p44551.624D0FA2.60f2effe-6dfe-4a0c-9bef-123456789/download', 'fileSize': 1071, 'expiration': 1657065600000}

3) Download the report with the url obtained in Get

```
def sb_download_snapshot():

    url = 'https://advertising-api-eu.amazon.com/v1/snapshots/amzn1.clicksAPI.v1.p44551.624D0FA2.60f2effe-6dfe-4a0c-9bef-123456789/download'

    download_type = "json"

    result = sponsored_brands.Snapshots(account=store, marketplace=marketplace, debug=True).download_snapshot(
        url=url,
        format=download_type
    )

    payload = result.payload

    logging.info(payload)
```

And you will get a json file:

axxxxxxx-entityzzzzz-snapshot-campaign-cdb2b28c-6e48-4354-870b-123456789.json

Please let me know if is working for you and I will close the issue.

**Comment by denisneuf** [comment]
@KiranKowlgi #closed

**Comment by KiranKowlgi** [comment]
Awesome work @denisneuf

I'll pull the latest and run tests and get back asap to confirm all is ok.

**Comment by KiranKowlgi** [comment]
@denisneuf I tested a few APIs and it looks good to go!!! great work and thanks for the quick turnaround. I will be sure to send a few beers your way :)
