### ISSUE TITLE
Request捕获异常的顺序错误

### ISSUE THREAD

**Issue by mkdir700** [denisneuf/python-amazon-ad-api#4]
https://github.com/denisneuf/python-amazon-ad-api/blob/f0cf04163551494c3637c86a4531d52168593d80/ad_api/base/client.py#L68

https://github.com/denisneuf/python-amazon-ad-api/blob/f0cf04163551494c3637c86a4531d52168593d80/ad_api/base/client.py#L76

`RequestException`是`ConnectionError`的基类，我认为`ConnectionError`应该在`RequestException`的前面被捕获。

**Comment by denisneuf** [comment]
I have altered the order as it makes sense. It will appear in the next release as I have to add some other functions. Thank you.
