### ISSUE TITLE
SD Snapshots - Download issue for 'gzip' mode

### ISSUE THREAD

**Issue by KiranKowlgi** [denisneuf/python-amazon-ad-api#42]
**Describe the bug**
Unlike SP/SB it seems SD snapshots already return data in gzipped format i.e the response contains **0x1f 0x8b** as the starting bytes.

**To Reproduce**
1. Request for a SD Snapshot
2. Download it in 'gzip' mode
3. See error

**Expected behavior**
If response already contains the starting bytes denoting **gzipped** content then the same logic should apply as the code does currently wth csv or data modes etc.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 101.0.4951.41

**Comment by denisneuf** [comment]
I am not sure If I get the point.
If you download the SD Snapshot as "gzip":

```
    download_type = "gzip"

    result = sponsored_display.Snapshots(debug=True).download_snapshot(
        url=url,
        file="039c59af-2e09-4eee-994b-b20cbc6a40c2",
        format=download_type
    )
```

I get a file named as file parameter:
039c59af-2e09-4eee-994b-b20cbc6a40c2.json.gz (size: 969 bytes)

If I uncompress it:
039c59af-2e09-4eee-994b-b20cbc6a40c2 (size: 6KB)

Which is itself a json file with the snapshot requested.

What is the problem?
