### ISSUE TITLE
Attribution missing

### ISSUE THREAD

**Issue by saleweaver** [denisneuf/python-amazon-ad-api#7]
Hi,

thank you that you like my code! 
Please add the required attribution to my code. 

Thank you!

https://github.com/saleweaver/python-amazon-sp-api

**Comment by denisneuf** [comment]
Hi Michael, please check if the attribution is correct:
https://github.com/denisneuf/python-amazon-ad-api/blob/main/LICENSE
Anything let me know, kindest regards!

**Comment by saleweaver** [comment]
Thank you. I was thinking about including the Advertising API into my package, but you've already done it. Thanks for that!
