### ISSUE TITLE
Error code 422

### ISSUE THREAD

**Issue by t3ch9** [denisneuf/python-amazon-ad-api#90]
Using version 0.3.4, getting error code 422 when calling:

sponsored_products.BidRecommendations(marketplace=Marketplaces.NA, credentials=my_credentials, debug=True).get_keywords_bid_recommendations(body)

AND

sponsored_products.BidRecommendations(marketplace=Marketplaces.NA, credentials=my_credentials, debug=True).get_targets_bid_recommendations(body)

AND

sponsored_brands.BidRecommendations(marketplace=Marketplaces.NA, credentials=my_credentials, debug=True).get_bid_recommendations(body) 

Same error for all the above calls:

 'payload': {'code': '422',
             'details': "Unrecognized token 'adGroupId': was expecting",
             'requestId': '93Q93BW8PA5SSQ24Y65G'}}

Other API calls for BidRecommendations for SP and SB are working correctly.

**Comment by denisneuf** [comment]
Can you comment if you solved the problem? It could help others if they find same issue.

**Comment by t3ch9** [comment]
Would help if documentation included the requirement for using "body=json.dumps(data)" based on the endpoint.
